# Generated by Django 2.2.4 on 2019-08-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(db_index=True, max_length=150, unique=True)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('login', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
