# Generated by Django 2.2.4 on 2019-08-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0002_auto_20190821_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyUsers',
        ),
    ]
