# Generated by Django 2.2.4 on 2019-08-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companyusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('s_title', models.CharField(db_index=True, max_length=150)),
                ('ur_forma', models.CharField(blank=True, choices=[('ОАО', 'ОАО'), ('ООО', 'ООО'), ('ЗАО', 'ЗАО'), ('ИП', 'ИП'), ('НР', 'Нерезидент')], db_index=True, max_length=3)),
                ('inn', models.CharField(db_index=True, max_length=12, unique=True)),
                ('kpp', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dolg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob_ras', models.CharField(blank=True, db_index=True, max_length=150)),
                ('date_r', models.DateField()),
                ('pogashen', models.BooleanField()),
                ('perv_summa', models.FloatField()),
                ('ost_summa', models.FloatField()),
                ('date_pogashenia', models.DateField()),
                ('prosr', models.IntegerField()),
                ('dogovor', models.CharField(blank=True, db_index=True, max_length=150)),
                ('uiid_dolg', models.CharField(max_length=40)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitor', to='api.Debitor')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kreditor', to='api.Debitor')),
            ],
        ),
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('s_title', models.CharField(max_length=3)),
                ('kod', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OutputId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uiid', models.CharField(max_length=40)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Debitor')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_d', models.DateField()),
                ('summ', models.FloatField()),
                ('document', models.CharField(blank=True, db_index=True, max_length=150)),
                ('uiid_document', models.CharField(max_length=40)),
                ('dolg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dolg')),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Valuta')),
            ],
        ),
        migrations.AddField(
            model_name='dolg',
            name='valuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Valuta'),
        ),
    ]
