# Generated by Django 2.2.4 on 2019-08-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190821_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='uiid_document',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='SvLitsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_svyzi', models.CharField(db_index=True, max_length=50)),
                ('osn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osn', to='api.Debitor')),
                ('sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sv', to='api.Debitor')),
            ],
        ),
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.IntegerField()),
                ('doch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doch', to='api.Debitor')),
                ('vlad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlad', to='api.Debitor')),
            ],
        ),
    ]
