# Generated by Django 2.2.4 on 2019-08-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190821_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dolg',
            name='debitor',
        ),
        migrations.RemoveField(
            model_name='dolg',
            name='id_company',
        ),
        migrations.RemoveField(
            model_name='dolg',
            name='kreditor',
        ),
        migrations.RemoveField(
            model_name='dolg',
            name='valuta',
        ),
        migrations.RemoveField(
            model_name='history',
            name='dolg',
        ),
        migrations.RemoveField(
            model_name='history',
            name='valuta',
        ),
        migrations.RemoveField(
            model_name='outputid',
            name='debitor',
        ),
        migrations.RemoveField(
            model_name='outputid',
            name='id_company',
        ),
        migrations.RemoveField(
            model_name='svlitsa',
            name='osn',
        ),
        migrations.RemoveField(
            model_name='svlitsa',
            name='sv',
        ),
        migrations.DeleteModel(
            name='Acc',
        ),
        migrations.DeleteModel(
            name='Debitor',
        ),
        migrations.DeleteModel(
            name='Dolg',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='OutputId',
        ),
        migrations.DeleteModel(
            name='SvLitsa',
        ),
    ]
