# Generated by Django 2.2.4 on 2019-08-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190823_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
                ('p_title', models.CharField(db_index=True, max_length=150)),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('ur_forma', models.CharField(blank=True, choices=[('ОАО', 'ОАО'), ('ООО', 'ООО'), ('ЗАО', 'ЗАО'), ('ИП', 'ИП'), ('НР', 'Нерезидент')], db_index=True, max_length=3)),
                ('inn', models.CharField(db_index=True, max_length=12, unique=True)),
                ('kpp', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=150)),
                ('date', models.DateField()),
                ('date_end', models.DateField()),
                ('uiid', models.CharField(db_index=True, max_length=40)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dogovor_debitor', to='api.Debitor')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dogovor_kreditor', to='api.Debitor')),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Valuta')),
            ],
        ),
        migrations.CreateModel(
            name='ObRash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=150)),
                ('uiid', models.CharField(db_index=True, max_length=40)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ObRash_debitor', to='api.Debitor')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ObRash_kreditor', to='api.Debitor')),
            ],
        ),
        migrations.CreateModel(
            name='SvLitsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_svyzi', models.CharField(db_index=True, max_length=50)),
                ('osn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osn', to='api.Debitor')),
                ('sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sv', to='api.Debitor')),
            ],
        ),
        migrations.CreateModel(
            name='OutputId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uiid', models.CharField(max_length=40)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Debitor')),
                ('dogovor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dogovor')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('ob_rash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ObRash')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_d', models.DateField()),
                ('summ', models.FloatField()),
                ('document', models.CharField(blank=True, db_index=True, max_length=150)),
                ('uiid_document', models.CharField(blank=True, max_length=40)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('ob_rash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ObRash')),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Valuta')),
            ],
        ),
        migrations.CreateModel(
            name='Dolg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_r', models.DateField()),
                ('pogashen', models.BooleanField()),
                ('perv_summa', models.FloatField()),
                ('ost_summa', models.FloatField()),
                ('date_pogashenia', models.DateField()),
                ('prosr', models.IntegerField()),
                ('uiid_dolg', models.CharField(db_index=True, max_length=40)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitor', to='api.Debitor')),
                ('dogovor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogovor', to='api.Dogovor')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kreditor', to='api.Debitor')),
                ('ob_rash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_rash', to='api.ObRash')),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Valuta')),
            ],
        ),
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.IntegerField()),
                ('doch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doch', to='api.Debitor')),
                ('vlad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlad', to='api.Debitor')),
            ],
        ),
    ]
