# Generated by Django 2.2.4 on 2019-08-24 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_acc_debitor_dogovor_dolg_history_obrash_outputid_svlitsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputid',
            name='debitor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Debitor'),
        ),
        migrations.AlterField(
            model_name='outputid',
            name='dogovor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Dogovor'),
        ),
        migrations.AlterField(
            model_name='outputid',
            name='ob_rash',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.ObRash'),
        ),
    ]
