# Generated by Django 2.2.4 on 2019-08-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190824_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitor',
            name='slug',
            field=models.SlugField(default=models.CharField(blank=True, db_index=True, max_length=12), unique=True),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='kpp',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
