# Generated by Django 2.2.4 on 2019-08-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190824_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='valuta',
            name='kod',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
