# Generated by Django 2.2.4 on 2019-08-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190825_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitor',
            old_name='type',
            new_name='t_type',
        ),
    ]
