# Generated by Django 2.2.4 on 2019-08-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190825_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debitor',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='dogovor',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='dolg',
            options={'ordering': ['-date_r']},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date_d']},
        ),
        migrations.AlterField(
            model_name='debitor',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=models.CharField(blank=True, db_index=True, max_length=12), unique=True),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='ur_forma',
            field=models.CharField(blank=True, choices=[('ОАО', 'Открытое акционерное общество'), ('ООО', 'Общество с ограниченной ответственностью'), ('ЗАО', 'Закрытое акционерное общество'), ('ИП', 'Индивидуальный предприниматель'), ('НР', 'Нерезидент')], db_index=True, max_length=3),
        ),
    ]
