# Generated by Django 2.2.4 on 2019-08-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190826_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusers',
            name='d_key',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyusers',
            name='key',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companyusers',
            name='key_refresh',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
