# Generated by Django 2.2.4 on 2019-08-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190830_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitor',
            name='u_adress',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
