# Generated by Django 2.2.4 on 2019-08-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190830_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitor',
            name='f_adress',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='telef',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='u_adress',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
