# Generated by Django 2.2.4 on 2019-08-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190830_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrForma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('ОАО', 'ОАО'), ('ООО', 'ООО'), ('ЗАО', 'ЗАО'), ('ИП', 'Индивидуальный предприниматель'), ('НР', 'Нерезидент'), ('', '')], db_index=True, max_length=60)),
                ('short', models.CharField(blank=True, db_index=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UrType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('ЮрЛицо', 'Юридическое лицо'), ('ФизЛиц', 'Физическое лицо'), ('ИП', 'ЗАО'), ('ИП', 'Индивидуальный предприниматель'), ('НР', 'Нерезидент'), ('', '')], db_index=True, max_length=60)),
                ('short', models.CharField(blank=True, db_index=True, max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='schet',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='schet',
            name='vlad',
        ),
        migrations.AlterModelOptions(
            name='debitor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dogovor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dolg',
            options={},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={},
        ),
        migrations.RemoveField(
            model_name='company',
            name='d_key',
        ),
        migrations.RemoveField(
            model_name='company',
            name='key',
        ),
        migrations.RemoveField(
            model_name='companyusers',
            name='d_key',
        ),
        migrations.RemoveField(
            model_name='companyusers',
            name='key',
        ),
        migrations.RemoveField(
            model_name='companyusers',
            name='key_refresh',
        ),
        migrations.RemoveField(
            model_name='debitor',
            name='slug',
        ),
        migrations.AlterField(
            model_name='debitor',
            name='f_adress',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='inn',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='kpp',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='telef',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='u_adress',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='ur_forma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UrForma'),
        ),
        migrations.AlterField(
            model_name='debitor',
            name='ur_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UrType'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='valuta',
            name='kod',
            field=models.CharField(max_length=3),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Schet',
        ),
    ]
