# Generated by Django 2.2.4 on 2019-08-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190830_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('bic', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='valuta',
            name='kod',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.CreateModel(
            name='Schet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_scheta', models.CharField(db_index=True, max_length=40)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bank')),
            ],
        ),
    ]
