# Generated by Django 2.2.4 on 2019-08-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190830_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='key',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companyusers',
            name='key',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companyusers',
            name='key_d',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='companyusers',
            name='key_refresh',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schet',
            name='vlad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Debitor'),
        ),
        migrations.AlterField(
            model_name='urtype',
            name='title',
            field=models.CharField(blank=True, choices=[('ЮрЛицо', 'Юридическое лицо'), ('ФизЛиц', 'Физическое лицо'), ('ИП', 'Индивидуальный предприниматель'), ('НР', 'Нерезидент'), ('', '')], db_index=True, max_length=60),
        ),
    ]
