# Generated by Django 2.2.4 on 2019-08-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190830_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urforma',
            name='title',
            field=models.CharField(blank=True, choices=[('ОАО', 'ОАО'), ('ООО', 'ООО'), ('ЗАО', 'ЗАО'), ('Индивидуальный предприниматель', 'ИП'), ('Нерезидент', 'НР'), ('', '')], db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='urtype',
            name='short',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='urtype',
            name='title',
            field=models.CharField(blank=True, choices=[('Юридическое лицо', 'ЮрЛицо'), ('Физическое лицо', 'ФизЛиц'), ('Индивидуальный предприниматель', 'ИП'), ('Нерезидент', 'НР'), ('', '')], db_index=True, max_length=60),
        ),
    ]
