# Generated by Django 2.2.4 on 2019-08-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_debitor_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debitor',
            options={'ordering': ['title']},
        ),
    ]
